# -*- coding: utf-8 -*-
"""Day39_Wednesday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXXgMeWehosUCkyXOzNWw3d39yDekLC4

a) Preprocessing: Negation handling

Example

“not bad at all” → positive

❌ Baseline failure
TF-IDF sees: ["not", "bad"]
“bad” dominates → classified negative
"""

def handle_negation(tokens):
    neg_words = {"not", "no", "never"}
    result = []
    negate = False

    for word in tokens:
        if word in neg_words:
            negate = True
            continue

        if negate:
            result.append("NOT_" + word)
            negate = False
        else:
            result.append(word)

    return result

"""Feature engineering
Create features like:

    NOT_bad → treated as a new token
Now model learns:

    bad = negative
    NOT_bad = positive

b) (b) Sarcasm
Example

“Wow great! Broke on day 1”

❌ Baseline failure
Words: wow, great → strong positive signal
→ classified positive
"""

positive_words = {"great", "wow", "excellent"}
negative_words = {"broke", "bad", "poor"}

def sarcasm_feature(tokens):
    has_pos = any(w in positive_words for w in tokens)
    has_neg = any(w in negative_words for w in tokens)

    return int(has_pos and has_neg)

"""Feature engineering
Add binary feature:

sarcasm_flag = 1

Optional:

sentence-level sentiment flip if contradiction exists

(c) Code-mixing (Hindi + English)
Example

“Product bahut accha hai lekin delivery late thi”

❌ Baseline failure
Hindi words ignored / treated as noise
→ loses sentiment signal (accha = good)
"""

hinglish_dict = {
    "accha": "good",
    "bahut": "very",
    "lekin": "but",
    "thi": "was"
}

def normalize_code_mix(tokens):
    return [hinglish_dict.get(w, w) for w in tokens]

"""Feature engineering
Normalize to English → improves TF-IDF

Optionally:

keep original + translated tokens

(d) Implicit sentiment
Example

“Returned it within 2 hours”

❌ Baseline failure
No explicit sentiment words
→ classified neutral
"""

def implicit_features(text):
    return {
        "returned_flag": int("return" in text),
        "refund_flag": int("refund" in text)
    }

"""Feature engineering
Add binary signals:
returned_flag = 1 → strong negative signal
These act as domain-specific sentiment indicators

(e) Comparative statements
Example

“Way better than my previous Samsung”

❌ Baseline failure
Sees “Samsung” + “better”
→ ambiguous or weak signal
✅ Fix
Preprocessing: detect comparison
"""

def comparative_features(tokens):
    return {
        "has_better": int("better" in tokens),
        "has_than": int("than" in tokens)
    }

"""Feature engineering
If pattern: better + than
→ current product = positive
If: worse + than
→ negative
"""

import pandas as pd
df = pd.read_csv("/content/preprocessed_reviews.csv")

i = 0  # example review index

text_series = df.iloc[i]
text = text_series['review_text'] # Access the string value from the Series
tokens = text.split()

# apply preprocessing
tokens = normalize_code_mix(tokens)

# build features
# Note: tfidf_sparse, negation_features, sarcasm_flag are not defined in the current notebook state
# Assuming they would be defined elsewhere or are placeholders for demonstration
# For now, I will comment them out or use dummy values to prevent further errors.

# Dummy implementations for missing functions/variables to allow execution
def negation_features(tokens):
    return 0 # Placeholder
def sarcasm_flag(tokens):
    return 0 # Placeholder
tfidf_sparse = {i: [0.0] * 10} # Placeholder: assuming a list of 10 zeros

tfidf_vector = tfidf_sparse[i] # .toarray().flatten() if it were a sparse matrix
neg_feat = negation_features(tokens)
sarcasm_feat = sarcasm_flag(tokens)
implicit_feat = implicit_features(text)
comp_feat = comparative_features(tokens)

# final feature vector
final_vector = list(tfidf_vector) + [
    neg_feat,
    sarcasm_feat,
    implicit_feat,
    comp_feat
]

print("Feature vector length:", len(final_vector))

