# -*- coding: utf-8 -*-
"""Day_38_Tuesday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoRG_d5U6dXbPq0pf7Jpb-4d5Bf7o78X
"""

import pandas as pd

df = pd.read_csv('/content/preprocessed_reviews.csv')

df.head()

sentences = df['review_text'].str.split().tolist()

!pip install gensim
from gensim.models import Word2Vec

model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

"""(a) Polysemy: “cheap” has ONE vector

Word2Vec assigns one embedding per word, regardless of meaning.
"""

print(model.wv['cheap'][:10])  # first 10 values

"""Cosine similarity"""

print("affordable" in model.wv.key_to_index)
print("flimsy" in model.wv.key_to_index)

model.wv.most_similar("cheap", topn=10)

from numpy import dot
from numpy.linalg import norm

def cosine(w1, w2):
    return dot(model.wv[w1], model.wv[w2]) / (norm(model.wv[w1]) * norm(model.wv[w2]))

print("cheap vs price:", cosine("cheap", "price"))
print("cheap vs poor:", cosine("cheap", "poor"))

"""Interpretation

The word “cheap” shows high similarity with both “price” (affordable sense) and “poor” (low-quality sense). This demonstrates that Word2Vec assigns a single vector to “cheap”, capturing both meanings together rather than separating them.

(b) Disambiguation system (improved with your words)

Step 1: Define anchors
"""

affordable_anchor = model.wv["price"]
quality_anchor = model.wv["poor"]

"""Step 2: Context vector"""

def get_context_vector(sentence):
    words = sentence.lower().split()
    vectors = [model.wv[w] for w in words if w in model.wv and w != "cheap"]

    if len(vectors) == 0:
        return None

    return sum(vectors) / len(vectors)

"""Step 3: Classification"""

def cosine_vec(v1, v2):
    return dot(v1, v2) / (norm(v1) * norm(v2))

def classify_cheap(sentence):
    context_vec = get_context_vector(sentence)

    if context_vec is None:
        return "Unknown"

    sim_affordable = cosine_vec(context_vec, affordable_anchor)
    sim_quality = cosine_vec(context_vec, quality_anchor)

    if sim_affordable > sim_quality:
        return "Affordable"
    else:
        return "Low-quality"

print(classify_cheap("this is cheap and worth the price"))
print(classify_cheap("this looks cheap and poor quality"))

"""Explanation

The system computes the average embedding of context words and compares it with anchor vectors representing different meanings of “cheap”. The meaning is assigned based on higher cosine similarity.

(c) Window size comparison

A smaller window size (e.g., 2) captures syntactic relationships because it focuses on immediate neighboring words such as modifiers and grammatical structure. A larger window size (e.g., 10) captures semantic relationships by incorporating a broader context, allowing the model to learn topic-level associations. Therefore, window size 2 is better for syntactic similarity, while window size 10 is better for semantic similarity.

Uutput shows:

“cheap” is close to both:
    “price” → positive sense
    “poor” → negative sense

This is direct empirical proof of polysemy limitation in Word2Vec.
"""

