# -*- coding: utf-8 -*-
"""Day_37_Monday_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sExDsrA7YnTyPVJRoK8RvNt-xpuhAw4M
"""

import pandas as pd

df_full = pd.read_csv("/content/shopsense_reviews.csv")
df_full.head()

df = df_full["review_text"]
df.head()

df = df.dropna()
df.head()

import re
def remove_tags(raw):
  return re.sub(r"<.*?>","", raw)

df = df.astype(str).apply(remove_tags)
df.head()

df = df.apply(lambda x: x.lower())
df.head()

df = df.apply(lambda x: re.findall(r"[a-z]+", x))
df = df.apply(lambda x: " ".join(x))

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw_list = stopwords.words('english')

def remove_stopwords(text):
    words = text.split()
    filtered = [word for word in words if word not in sw_list]
    return " ".join(filtered)

df = df.apply(remove_stopwords)
df

"""(a) Compute the full TF-IDF matrix for all 10,000 reviews (use sparse representation if needed).

Step 1: Tokenization

Convert each review into a list of words.
"""

docs_tokens = df.apply(lambda x: x.split()).tolist()

"""Step 2: Build Vocabulary

Create a mapping: word → index
"""

vocab = {}
for tokens in docs_tokens:
    for word in tokens:
        if word not in vocab:
            vocab[word] = len(vocab)

"""Step 3: Compute Document Frequency (DF)"""

df_count = [0] * len(vocab)

for tokens in docs_tokens:
    for word in set(tokens):  # unique words per doc
        df_count[vocab[word]] += 1

import math

N = len(docs_tokens)

idf = [0] * len(vocab)
for word, idx in vocab.items():
    idf[idx] = math.log(N / (df_count[idx] + 1))

"""Step 5: Build Sparse TF-IDF Matrix"""

from collections import Counter
from scipy.sparse import csr_matrix

data = []
indices = []
indptr = [0]

for tokens in docs_tokens:
    word_count = Counter(tokens)
    total_words = len(tokens)

    for word, count in word_count.items():
        idx = vocab[word]
        tf = count / total_words
        tfidf = tf * idf[idx]

        data.append(tfidf)
        indices.append(idx)

    indptr.append(len(data))

tfidf_sparse = csr_matrix((data, indices, indptr),
                          shape=(N, len(vocab)))

print("Shape:", tfidf_sparse.shape)
print("Non-zero values:", tfidf_sparse.nnz)

print(tfidf_sparse)

"""b) ) Given the query 'wireless earbuds battery life poor', rank the top-5 most relevant reviews using cosine similarity against TF-IDF vectors.

Step 1: Prepare the query (same preprocessing)
"""

query = "wireless earbuds battery life poor"

def preprocess_query(text):
    text = remove_tags(text)
    text = text.lower()
    words = re.findall(r"[a-z]+", text)
    words = [w for w in words if w not in sw_list]
    return words

query_tokens = preprocess_query(query)

"""Step 2: Convert query → TF-IDF vector"""

import numpy as np
query_vec = np.zeros(len(vocab))

word_count = Counter(query_tokens)
total_words = len(query_tokens)

for word, count in word_count.items():
    if word in vocab:   # ignore unseen words
        idx = vocab[word]
        tf = count / total_words
        query_vec[idx] = tf * idf[idx]

"""Step 3: Cosine similarity"""

from numpy.linalg import norm

scores = []

for i in range(tfidf_sparse.shape[0]):
    doc_vec = tfidf_sparse[i].toarray().flatten()

    if norm(doc_vec) == 0 or norm(query_vec) == 0:
        similarity = 0
    else:
        similarity = np.dot(doc_vec, query_vec) / (norm(doc_vec) * norm(query_vec))

    scores.append(similarity)

"""Step 4: Get Top-5 Reviews"""

top5_idx = np.argsort(scores)[-5:][::-1]

for i in top5_idx:
    print("Score:", scores[i])
    print("Review:", df.iloc[i])
    print("-" * 50)

"""c) Compare with TfidfVectorizer

Step 1: Generate sklearn TF-IDF
"""

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english'
)

X_sklearn = vectorizer.fit_transform(df)   # df = cleaned text

"""Step 2: Align vocabularies

Your vocab ≠ sklearn vocab → must align before comparison.
"""

sk_vocab = vectorizer.vocabulary_

common_words = set(vocab.keys()).intersection(set(sk_vocab.keys()))

# indices mapping
our_idx = [vocab[w] for w in common_words]
sk_idx = [sk_vocab[w] for w in common_words]

"""Step 3: Extract aligned matrices"""

X_ours = tfidf_sparse[:, our_idx].toarray()
X_sk = X_sklearn[:, sk_idx].toarray()

"""Step 4: Compute average L2 difference"""

diff = X_ours - X_sk
l2_per_doc = np.linalg.norm(diff, axis=1)

avg_l2 = np.mean(l2_per_doc)
print("Average L2 difference:", avg_l2)

"""d) Highest average TF-IDF word (Electronics)

Step 1: Filter Electronics reviews
"""

electronics_df = df_full[df_full['category'] == 'Electronics']
electronics_text = electronics_df['review_text']

"""Step 2: Recompute TF-IDF (or reuse pipeline)"""

import re

def preprocess(text):
    text = remove_tags(str(text))      # remove HTML
    text = text.lower()                # lowercase
    words = re.findall(r"[a-z]+", text)  # keep only letters
    words = [w for w in words if w not in sw_list]  # remove stopwords
    return words

docs_tokens = electronics_text.apply(preprocess).tolist()

"""Step 3: Get average TF-IDF per word"""

electronics_mask = df_full.loc[df.index]['category'] == 'Electronics'

# subset matrix using the boolean mask
X_elec = tfidf_sparse[electronics_mask.values]

# mean TF-IDF per column (word)
avg_tfidf = X_elec.mean(axis=0).A1  # convert to 1D array

# find top word
top_idx = np.argmax(avg_tfidf)

# reverse vocab
index_to_word = {idx: word for word, idx in vocab.items()}

top_word = index_to_word[top_idx]
print("Top word:", top_word)

"""The word “camera” has the highest average TF-IDF score because it appears frequently in Electronics reviews while remaining relatively specific to that category. It is commonly used when describing product features such as image quality, resolution, and performance in devices like smartphones and cameras. At the same time, it is not widely used across other categories, which increases its inverse document frequency. This combination of high term frequency and relatively high inverse document frequency results in the highest average TF-IDF score."""

